# Generated by Django 4.2.7 on 2025-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=200)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand_score', models.IntegerField()),
                ('avg_size_sqft', models.IntegerField()),
                ('transactions', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Real Estate Data',
                'verbose_name_plural': 'Real Estate Data',
                'ordering': ['area', 'year'],
            },
        ),
    ]
